# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/gyro_constraints.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_SPI_ip_0_0/design_2_SPI_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_SPI_ip_0_0 || ORIG_REF_NAME==design_2_SPI_ip_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xbar_0/design_2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xbar_0 || ORIG_REF_NAME==design_2_xbar_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ps7_0_axi_periph_0/design_2_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_RxFIFO_0/design_2_RxFIFO_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_RxFIFO_0 || ORIG_REF_NAME==design_2_RxFIFO_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_BiDirChannels_0_0/design_2_BiDirChannels_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_BiDirChannels_0_0 || ORIG_REF_NAME==design_2_BiDirChannels_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_stream_txfifo_0_2/design_2_axis_stream_txfifo_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_stream_txfifo_0_2 || ORIG_REF_NAME==design_2_axis_stream_txfifo_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconcat_1_0/design_2_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconcat_1_0 || ORIG_REF_NAME==design_2_xlconcat_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_dma_0_0/design_2_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_dma_0_0 || ORIG_REF_NAME==design_2_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_proc_sys_reset_0_1/design_2_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_1 || ORIG_REF_NAME==design_2_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_proc_sys_reset_0_2/design_2_proc_sys_reset_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_2 || ORIG_REF_NAME==design_2_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_0 || ORIG_REF_NAME==design_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_smartconnect_0_0/design_2_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_smartconnect_0_0 || ORIG_REF_NAME==design_2_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_5/design_2_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_auto_pc_5 || ORIG_REF_NAME==design_2_auto_pc_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_auto_pc_0 || ORIG_REF_NAME==design_2_auto_pc_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_1/design_2_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_auto_pc_1 || ORIG_REF_NAME==design_2_auto_pc_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_2/design_2_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_auto_pc_2 || ORIG_REF_NAME==design_2_auto_pc_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_3/design_2_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_auto_pc_3 || ORIG_REF_NAME==design_2_auto_pc_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_4/design_2_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_auto_pc_4 || ORIG_REF_NAME==design_2_auto_pc_4} -quiet] -quiet

# XDC: bd/design_2/design_2_ooc.xdc
