#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : design_2.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Apr 01 14:39:34 PDT 2022
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_2.sh [-help]
# usage: design_2.sh [-lib_map_path]
# usage: design_2.sh [-noclean_files]
# usage: design_2.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_2.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm lib_pkg_v1_0_2 fifo_generator_v13_2_6 lib_fifo_v1_0_15 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_27 axi_sg_v4_1_14 axi_dma_v7_1_26 xil_defaultlib axi_infrastructure_v1_1_0 axi_vip_v1_1_11 processing_system7_vip_v1_0_13 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_25 axi_data_fifo_v2_1_24 axi_crossbar_v2_1_26 proc_sys_reset_v5_0_13 xlconstant_v1_1_7 smartconnect_v1_0 xlconcat_v2_1_4 axi_protocol_converter_v2_1_25)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_2.sh - Script generated by export_simulation (Vivado v2021.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/8ae1/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_6 $vhdlan_opts \
    "$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/8ae1/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/8ae1/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_15 $vhdlan_opts \
    "$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/a4ed/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_27 $vhdlan_opts \
    "$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/9b19/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_14 $vhdlan_opts \
    "$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/bcf6/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_26 $vhdlan_opts \
    "$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/69a4/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_dma_0_0/sim/design_2_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ipshared/2e00/hdl/SPI_ip_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/design_2/ipshared/2e00/hdl/SPI_ip_v1_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_SPI_ip_0_0/sim/design_2_SPI_ip_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_11 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/63b7/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_processing_system7_0_0/sim/design_2_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/e1e6/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_24 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/fa53/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ac57/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_xbar_0/sim/design_2_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ipshared/84ab/hdl/axis_stream_fifo_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/design_2/ipshared/84ab/hdl/axis_stream_txfifo_v2_0_S00_AXIS.sv" \
    "$ref_dir/../../../bd/design_2/ipshared/84ab/src/syncr.sv" \
    "$ref_dir/../../../bd/design_2/ipshared/84ab/src/gen_async_que.sv" \
    "$ref_dir/../../../bd/design_2/ipshared/84ab/hdl/axis_stream_fifo_v1_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_RxFIFO_0/sim/design_2_RxFIFO_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ipshared/b070/hdl/BiDirChannels_v1_0_S00_AXI.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ipshared/b070/hdl/BiDirChannels_v1_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_BiDirChannels_0_0/sim/design_2_BiDirChannels_0_0.sv" \
    "$ref_dir/../../../bd/design_2/ipshared/77aa/hdl/axis_stream_txfifo_v2_0_S00_AXI.sv" \
    "$ref_dir/../../../bd/design_2/ipshared/77aa/hdl/axis_stream_txfifo_v2_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axis_stream_txfifo_0_2/sim/design_2_axis_stream_txfifo_0_2.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_proc_sys_reset_0_1/sim/design_2_proc_sys_reset_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_0c5c_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_0c5c_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_0c5c_arsw_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_0c5c_rsw_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_0c5c_awsw_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_0c5c_wsw_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_0c5c_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_0c5c_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_0c5c_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_0c5c_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_0c5c_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_0c5c_sarn_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_0c5c_srn_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_0c5c_sawn_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_0c5c_swn_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_0c5c_sbn_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_0c5c_s01mmu_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_0c5c_s01tr_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_0c5c_s01sic_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_0c5c_s01a2s_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_0c5c_sarn_1.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_0c5c_srn_1.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_0c5c_s02mmu_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_0c5c_s02tr_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_0c5c_s02sic_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_0c5c_s02a2s_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_0c5c_sawn_1.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_0c5c_swn_1.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_0c5c_sbn_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_0c5c_m00s2a_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_0c5c_m00arn_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_0c5c_m00rn_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_0c5c_m00awn_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_0c5c_m00wn_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_0c5c_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/93a6/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_0c5c_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/bd_0/sim/bd_0c5c.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_smartconnect_0_0/sim/design_2_smartconnect_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_xlconcat_1_0/sim/design_2_xlconcat_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_proc_sys_reset_0_2/sim/design_2_proc_sys_reset_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/8fe4/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.srcs/sources_1/bd/design_2/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../gyro_tester_gold.gen/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"/proj/xbuilds/SWIP/2021.2_1021_0703/installs/lin64/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_auto_pc_5/sim/design_2_auto_pc_5.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_auto_pc_0/sim/design_2_auto_pc_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_auto_pc_1/sim/design_2_auto_pc_1.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_auto_pc_2/sim/design_2_auto_pc_2.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_auto_pc_3/sim/design_2_auto_pc_3.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_auto_pc_4/sim/design_2_auto_pc_4.v" \
    "$ref_dir/../../../bd/design_2/sim/design_2.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_2 xil_defaultlib.glbl -o design_2_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_2_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_2.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/cdickins/reuse/gyro_tester_gold-master/gyro_tester_gold/gyro_tester_gold/gyro_tester_gold.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_2_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_2_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_2.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_2.sh [-help]\n\
Usage: design_2.sh [-lib_map_path]\n\
Usage: design_2.sh [-reset_run]\n\
Usage: design_2.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
